### ISSUE TITLE
monitor memory

### ISSUE THREAD

**Issue by benjaminderei** [maxpumperla/hyperas#90] opened 2017-05-28 17:48 UTC
Anyway to monitor the central memory and gpu memory and kill the model if it exceed certain values ?

**Comment by maxpumperla** [comment] 2017-06-11 13:53
this has been an issue for a while and we still have not found a satisfying solution, however there is a ticket addressing the root cause of this already, see #16 (closing this one)

**Closed by maxpumperla** 2017-06-11 13:53 UTC
