### ISSUE TITLE
Avoid source manip with decorators

### ISSUE THREAD

**Issue by piccolbo** [maxpumperla/hyperas#70] opened 2017-03-11 06:49 UTC
Opening this per @maxpumperla suggestion on twitter.  A little pie in the sky suggestion, forgive me. I noticed the template mechanism and I went to look at the implementation, getsource and related. How robust is that manipulation? Can I pass a variable or a complex expression in between double curly brackets? Can't it be confused with a set of sets (which is not allowed in python, but still that's what a {{x}} tries to evaluate to. My point is that you don't really need a language extension, if I get it right. You need to call `model.fit` many times with different values for the parameters. This is also done in randomized testing and in python in particular in the package hypothesis. If you have a function `f(x,y)` you want to run on random inputs you just need to write

```
from hypothesis import given
from hypothesis.strategies import integers, booleans
@given(x = integers(), y = booleans())
def f(x,y):
```

will make f into a 0 non-default argument function that can just be called as f() and will run f(x,y) multiple times with random inputs. So I thought why not apply the same approach to hyperas to write something like

```
@optimize(dropout  = uniform(0,1), shape = choice([256, 512, 1024]))
def opt(dropout, shape):
return Sequential(
 ...
 Dropout(dropout = dropout))
```

The decorator just samples the parameters from the distribution, creates and fits as many models as necessary and computes summary stats. It may be a little more verbose then the {{}} notation and I am all for brevity, but doesn't tamper with Python's evaluation mechanism. In the spirit of least surprise and least effort, why not use a decorator? I may be missing the fundamental reason to use {{}}, but then it's good to have it written down for posterity. Thanks

**Comment by maxpumperla** [comment] 2017-03-12 15:05
Hey @piccolbo,

again, thanks for your suggestion, sounds very reasonable. Quick history on hyperas: At a point in time I was experimenting a lot (still am) with keras and hyperopt. works like a blast, everyone should do it. ;) However, for very quick experimentation I was always annoyed by the verbosity of the setup. In hyperopt you first have to setup a search space, which parameterises your fmin function. This is just fine, but you always have to touch two places to change your config. At the same time I was always very pleased with jinja templates when using little flask applications. Hence I wrote hyperas as shorthand for hyperopt+keras, knowing full-well it's limitations. Now, hyperas became unreasonably popular for what it does (given that you just use keras + hyperopt out of the box, which is also what hyperas translates back to).

Coming back to your suggestion, I thought about decorators as well. However, that would mean we're potentially back to modifying at two places. Speed is the only argument pro hyperas and in the end decorators are just function wrappers. 

Now, having said all that, there might still be value in this idea in terms of simplified notation (hyperopt's notation is somewhat complicated for novices). Also, I myself am really annoyed by how brittle the approach of hyperas is, believe me, although it works 100% fine for me, since I know how it's intended to be used. 

Alright, I'm very, very limited in my free time for OSS right now, but I promise you to pick up on the idea and come back to you. If, in the meantime, you have a draft of putting this idea into practice, feel free to share or open a PR. 

Best, -M

**Comment by piccolbo** [comment] 2017-03-16 00:32
Well, I think it's incumbent upon me to put some code behind my proposal since you are open to it. Thanks.

**Comment by maxpumperla** [comment] 2017-05-03 10:14
@piccolbo have you had any success with your approach? I still don't exactly see the benefit over pure keras+hyperopt, but I'm also still curious what you're up to

**Comment by piccolbo** [comment] 2017-05-05 04:58
No sorry, life is not cooperating. Will get back to you.

**Comment by piccolbo** [comment] 2017-05-05 05:37
I run into #27. It's closed so I will have to think what to do. If I can't run the tutorial, I am not going very far.

**Comment by maxpumperla** [comment] 2017-06-11 13:24
OK, I'd like to thank you for your proposal, but since I don't see any progress or activity, I will close this for now. Re-open whenever you find the time to discuss. thanks!

**Closed by maxpumperla** 2017-06-11 13:24 UTC

**Comment by piccolbo** [comment] 2017-06-11 19:01
Agree with closing, but I don't need any discussion to reopen, I need to be able to run the tutorial. As long as #27 is closed but unresolved, I consider this project unmaintained.  Thanks.

**Comment by maxpumperla** [comment] 2017-06-11 20:52
#27 concerns backward compatibility for older keras version, which has little to to with most of what is going on in what goes on  in the discussion there. Not even keras itself provides backward compatibility. You may or may not agree with this.

However, people still seem to have problems with running examples, which I surely want to support. That should be another issue then!

If you can't "run the tutorial", would you please file an issue? That would be great. Please provide a full example with a stack-trace of your error message.

We have unit and end-to-end tests for this project and while the coverage is not great, the build is currently green. If you care to look at the travis.yml, it's not that hard to install hyperas from a fresh linux box. Not sure about your setup, but I definitely want to help. As for the concrete example that people come back to in #27, it is included in the build:

https://github.com/maxpumperla/hyperas/blob/c36740b6dfc14b016427bff33c763443fe839c9a/tests/test_e2e.py#L82

Having that in mind, would you please tell me how I'm not supposed to consider #27 closed?

I honestly find it a little harsh to consider this "unmaintained", unless I learn what your specific problem is.

**Comment by piccolbo** [comment] 2017-06-12 01:12
OK so the problem is that people are experiencing the same symptoms and keep commenting on that ticket and you are relying on the title to say that's exclusively a backward compatibility issue, so you don't want to address the same problem if it affects the latest version and deps within the same ticket, even if the test case and error message is the same. So if I created a ticket that's identical but for the reference to the older version, you'd be willing to look into it. You may be right on this one that we are all hijacking #27 in a slightly new direction but you could also educate your users saying that they need to open a new ticket or it will go unadressed. You look at the comments post-closure covering more than a year and wonder if a comment was not warranted. You are right that "unmaintained" lacked some nuance. I should have said "not maintained to a level I am comfortable with, both as user or developer". Others may differ.

**Comment by maxpumperla** [comment] 2017-06-12 03:41
dude, I really don't think you get it. I get 100+ github notifications per day, of course I have to rely on certain things, otherwise I would go crazy. Doesn't mean I neglect things on purpose. Apart from a day job and a family, you think your regular open source monkey would do everything to comb through tickets post-closure? think again.

Wait, I need to educate ppl on this? If people necro in tickets without bothering about the context, clarifying or suggesting to reopen it, that is hardly my fault and not how the ticket system should be used. I just went quickly through the thread yesterday to assess your position, otherwise I was unaware of this. I can tell you from experience, there's a ton of maintainers who would take a "build is green, rtfm" view on this one.  

you may differ all you want and that's fine with me, but at the very least be polite, produce meaningful issues and be constructive about it. it's very easy to load it all off on someone else. talk is cheap.

**Comment by shadiakiki1986** [comment] 2017-10-27 07:35
I think all the tickets on `TypeError: require string label` boil down to users trying to directly run the model creation function that's supposed to get wrapped into `optim.minimize`. So for example in the readme, it would be like directly calling `model(...)`. That fails simply because python cannot run the templating in the braces, e.g. `{{uniform..}}`. The `def model(...)` function is in fact not a valid python function anymore, but rather a template (think jinja templating), and that is the basis of how hyperas simplifies usage of hyperopt by being a "very simple wrapper"

**Comment by maxpumperla** [comment] 2017-10-27 08:23
@shadiakiki1986 thanks for your support here. I'm really at a loss sometimes how to help in such cases properly. 

Usually people don't _want_ to provide full examples, so I can't reproduce the behaviour. Now, I've mentioned many times that this supposed "error" is covered by tests in travis, so it must be wrong usage. Whenever I dare to close one of these tickets, two others get opened. Or worse yet, people get a sense of entitlement out of it, as the gentleman above.

It's great that you found this, though!  Would you mind creating a PR for the readme in a small FAQ section? Nothing big, just essentially what you write above. That would help a lot, let me know!
