### ISSUE TITLE
Unable to run example code - TypeError('require string label')

### ISSUE THREAD

**Issue by bohoro** [maxpumperla/hyperas#106] opened 2017-06-27 12:23 UTC
Hi,

I am unable to run the first hyperas example.  Specifically this line:

```
>>> model.add(Dropout({{uniform(0, 1)}}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brohoro/Documents/PyProjects/envs/tensorflow/lib/python2.7/site-packages/hyperopt/pyll_utils.py", line 21, in wrapper
    raise TypeError('require string label')
```

The example without hyperas runs fine.

Here is my env

Python 2.7.13
Name: Keras
Version: 2.0.4
Name: hyperas
Version: 0.3
Name: hyperopt
Version: 0.1

I have tried this both via Jupyter and via the python interpreter.

Thanks

**Comment by maxpumperla** [comment] 2017-06-28 16:58
Hi @bohoro, does it work if you install hyperas from master? It's been ages since I got around to release a new version.

**Comment by huseynlilkin** [comment] 2017-06-28 21:54
There is also a problem with comments, try again after deleting comments in your code

**Comment by maxpumperla** [comment] 2017-06-29 04:40
@huseynlilkin while this is absolutely true, I don't think it relates to this issue.

**Comment by nchuramani** [comment] 2017-06-30 14:25
Hi @maxpumperla , I am facing the same problem with uniform and choice. I tried installing hyperas from master i.e. hyperas 0.4 but I am still facing the same issue.

**Comment by maxpumperla** [comment] 2017-07-11 11:44
sorry to hear that. will look into the issue once back from vacation

**Comment by Miladoooos** [comment] 2017-07-14 22:01
Hi 
I have the same issue with choice and uniform. Please if anyone has any suggestions, let me know!

**Comment by aydindemircioglu** [comment] 2017-07-26 09:44
same for me, though i did not use the example but hacked it directly into my unet network.
btw, is it supported to have images as labels?

**Comment by rcox771** [comment] 2017-07-31 20:34
I had the same error earlier today, but mine was caused by not using double curly braces around my choices. Do you have a spot in your code where you're missing an extra set of braces?

before:
`    model.compile(loss='categorical_crossentropy',
                  optimizer={choice(['rmsprop', 'adam', 'sgd'])},
                  metrics=['accuracy'])`

after:
`    model.compile(loss='categorical_crossentropy',
                  optimizer={{choice(['rmsprop', 'adam', 'sgd'])}},
                  metrics=['accuracy'])`

**Comment by aydindemircioglu** [comment] 2017-08-11 10:58
ok, at least in my case i realized that i call my network directly, did not see that (stupid me).
but i have still problems, a) i use python 2 and "from __future__ import division", which needs to
be handled in extract_imports in utils.py like         if 'print_function' in line or 'import division' in line:
b) i still get an error like 

Traceback (most recent call last):
  File "./hyperopt16bit.py", line 455, in <module>
    trials=Trials(15)) 
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 67, in minimize
    verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 133, in base_minimizer
    return_argmin=True),
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
IndexError: list index out of range

will see into it, what i am doing wrong.

**Comment by aydindemircioglu** [comment] 2017-08-12 07:36
and the other thing is that my code was calling a function to create the model, like 

```def getUNet(): 
...

def trainStep():
    model = getUNet()
```

now the issue is fixed on my side.

**Comment by hacheemaster** [comment] 2017-09-28 04:38
Any update on this issue? I'm still getting the 'require string label' error...

**Comment by nchuramani** [comment] 2017-09-28 08:15
HI,
For me, only the uniform gives me the error now. I removed uniform and it worked. I have the updated versions of keras and hyperopt and the hyperas version from git master.

**Comment by shadiakiki1986** [comment] 2017-10-27 07:25
You can't execute the model creation code directly in python. You need to wrap your code in a `def create_model(...): ...` function, and then call it from `optim.minimize(model=create_model,...` like in the example in the readme.

My understanding is that the reason for this is that hyperas works is by doing template replacement of everything in the `{{...}}` into a separate temporary file, and then running the model with the replaced braces.

**Closed** 2017-10-27 08:26 UTC

**Comment by kesarianubhav** [comment] 2018-05-21 11:49
I have a function named model wherein I am creating layers,fitting to data . And i am calling that fnc from opt.minimize . But  i am Still getting this error !! Any clues ??

**Comment by mbfair** [comment] 2018-07-24 12:52
Hello, I realize this is an older thread, but I am getting the same issue as @aydindemircioglu:

assert order[-1] == expr
IndexError: list index out of range

Do you have insight on what caused / solved this issue? TIA

**Comment by jcatanza** [comment] 2020-12-08 01:04
Why is the issue closed? 

It doesn't seem to be resolved. I (and others) still cannot run the example code without getting the 'require string label' error...

If the issue is resolved can someone please describe how they are able to run the code without getting this error?

**Comment by shadiakiki1986** [comment] 2020-12-08 01:46
Where's your code?

**Comment by JonnoFTW** [comment] 2020-12-08 01:47
I ran the simple.py example just now and it worked fine for me.

Steps:

```
git clone https://github.com/maxpumperla/hyperas
cd hyperas
python3 -m venv 
source venv/bin/activate
pip install -e .
pip install tensorflow
cd examples
# edit simple.py line 60 to epochs=1
python simple.py
```
