### ISSUE TITLE
Have an issue on pure pycharm file

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [maxpumperla/hyperas#53] opened 2016-12-05 06:55 UTC
@maxpumperla I am still confused how I should implement my code in pure pycharm?
it's my pure pycharm file:

`from __future__ import print_function
from hyperopt import Trials, STATUS_OK, tpe
from hyperas import optim
from hyperas.distributions import choice, uniform

from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import RMSprop

from keras.datasets import mnist
from keras.utils import np_utils

def data():
    """
    Data providing function:

    This function is separated from model() so that hyperopt
    won't reload data for each evaluation run.
    """
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
    X_train = X_train.reshape(60000, 784)
    X_test = X_test.reshape(10000, 784)
    X_train = X_train.astype('float32')
    X_test = X_test.astype('float32')
    X_train /= 255
    X_test /= 255
    nb_classes = 10
    Y_train = np_utils.to_categorical(y_train, nb_classes)
    Y_test = np_utils.to_categorical(y_test, nb_classes)
    return X_train, Y_train, X_test, Y_test

def model(X_train, Y_train, X_test, Y_test):
    """
    Model providing function:

    Create Keras model with double curly brackets dropped-in as needed.
    Return value has to be a valid python dictionary with two customary keys:
        - loss: Specify a numeric evaluation metric to be minimized
        - status: Just use STATUS_OK and see hyperopt documentation if not feasible
    The last one is optional, though recommended, namely:
        - model: specify the model just created so that we can later use it again.
    """
    model = Sequential()
    model.add(Dense(512, input_shape=(784,)))
    model.add(Activation('relu'))
    model.add(Dropout({{uniform(0, 1)}}))
    model.add(Dense({{choice([256, 512, 1024])}}))
    model.add(Activation('relu'))
    model.add(Dropout({{uniform(0, 1)}}))
    model.add(Dense(10))
    model.add(Activation('softmax'))

    rms = RMSprop()
    model.compile(loss='categorical_crossentropy', optimizer=rms, metrics=['accuracy'])

    model.fit(X_train, Y_train,
              batch_size={{choice([64, 128])}},
              nb_epoch=1,
              verbose=2,
              validation_data=(X_test, Y_test))
    score, acc = model.evaluate(X_test, Y_test, verbose=0)
    print('Test accuracy:', acc)
    return {'loss': -acc, 'status': STATUS_OK, 'model': model}

X_train, Y_train, X_test, Y_test = data()

best_run, best_model = optim.minimize(model=model,
                                      data=data,
                                      algo=tpe.suggest,
                                      max_evals=5,
                                      trials=Trials(), notebook_name="simple_notebook")
best_model.save("best_model.h5")
print("Evalutation of best performing model:")
print(best_model.evaluate(X_test, Y_test))
`
Should I crate any notebook file? 
1) I create and empty it. then run my code and get the error. "NameError: name 'mnist' is not defined"
2) then I copy-paste my code into notebook, and run my code. again get the error "NameError: name 'mnist' is not defined".
3) I run the notebook directly, everything is OK. then run pycharm file and it is OK as well.
4) empty the notebook, and run pycharm code.. it is still surprisingly working... 

I would be grateful if you could let me know how to utilize hyperas in pure pycharm code...

**Comment by maxpumperla** [comment] 2016-12-05 08:13
thanks for the feedback, I'll continue working on it. To be clear, I don't use pycharm and have no experience with it. The only thing I managed to get rid of is the `import _py..._` error you reported earlier.

**Comment by ErmiaAzarkhalili** [comment] 2016-12-05 08:20
No problem, it is not a big deal at all, I forget utilizing pycharm on the hyperas and utilize pure Ipython instead untill finding the solution and let you know to update accordingly...

**Comment by ErmiaAzarkhalili** [comment] 2016-12-05 11:00
it's my example code with properly work on pure Ipython

`
from hyperopt import Trials, STATUS_OK, tpe
from hyperas import optim
from hyperas.distributions import choice, uniform, conditional
from keras.datasets import mnist
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers.normalization import BatchNormalization
from keras.layers.advanced_activations import LeakyReLU, SReLU, PReLU, ThresholdedReLU


def data():
    """
    Data providing function:

    This function is separated from model() so that hyperopt
    won't reload data for each evaluation run.
    """
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
    X_train = X_train.reshape(60000, 784)
    X_test = X_test.reshape(10000, 784)
    X_train = X_train.astype('float32')
    X_test = X_test.astype('float32')
    X_train /= 255
    X_test /= 255
    nb_classes = 10
    Y_train = np_utils.to_categorical(y_train, nb_classes)
    Y_test = np_utils.to_categorical(y_test, nb_classes)
    return X_train, Y_train, X_test, Y_test


def model(X_train, Y_train, X_test, Y_test):
    """
    Model providing function:

    Create Keras model with double curly brackets dropped-in as needed.
    Return value has to be a valid python dictionary with two customary keys:
        - loss: Specify a numeric evaluation metric to be minimized
        - status: Just use STATUS_OK and see hyperopt documentation if not feasible
    The last one is optional, though recommended, namely:
        - model: specify the model just created so that we can later use it again.
    """
    model = Sequential()
    model.add(Dense(512, input_shape=(784,)))
    model.add(BatchNormalization())
    model.add(Activation({{choice(['relu', 'softplus', 'softsign'])}}))
    model.add(Dropout({{uniform(0, 0.5)}}))

    model.add(Dense({{choice([32, 64, 128, 256, 512, 768, 1024])}}))
    model.add(BatchNormalization())
    model.add(Activation({{choice(['relu', 'sigmoid', 'hard_sigmoid', 'softmax', 'tanh', 'softplus', 'softsign'])}}))
    model.add(Dropout({{uniform(0, 0.5)}}))

    # If we choose 'four', add an additional fourth layer
    # if conditional({{choice(['three', 'four'])}}) == 'four':
    for _ in range(1, conditional({{choice([1, 4, 8, 16])}})):
        # model.add(Dense(100))
        model.add(Dense({{choice([32, 64, 128, 256, 512, 768, 1024])}}))
        model.add(BatchNormalization())
        # We can also choose between complete sets of layers
        model.add({{choice([Dropout(0.5), Dropout(0.25),
                            Activation('linear'), Activation('relu'), Activation('hard_sigmoid'), Activation('softmax')])}})
        model.add(Activation('relu'))

    model.add(Dense(10))
    model.add(BatchNormalization())
    model.add(Activation('softmax'))

    model.compile(loss='categorical_crossentropy', metrics=['accuracy'],
                  optimizer={{choice(['rmsprop', 'adam', 'sgd', 'nadam', 'adadelta', 'adamax', 'adagrad'])}})

    model.fit(X_train, Y_train,
              batch_size={{choice([64, 128, 256, 512, 768, 1024])}},
              nb_epoch=1,
              verbose=2,
              validation_data=(X_test, Y_test))
    score, acc = model.evaluate(X_test, Y_test, verbose=0)
    print('Test accuracy:', acc)
    return {'loss': -acc, 'status': STATUS_OK, 'model': model}


best_run, best_model = optim.minimize(model=model,
                                      data=data,
                                      algo=tpe.suggest,
                                      max_evals=100,
                                      trials=Trials(), notebook_name="simple_notebook")
best_model.save("best_model.h5")
X_train, Y_train, X_test, Y_test = data()
print("Evaluation of best performing model:")
print(best_model.evaluate(X_test, Y_test))
print(best_model.summary())
`

it's my temp_model.py file
`
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials
from hyperas.distributions import conditional

"""
Data providing function:

This function is separated from model() so that hyperopt
won't reload data for each evaluation run.
"""
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
nb_classes = 10
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)


def keras_fmin_fnct(space):

    """
    Model providing function:

    Create Keras model with double curly brackets dropped-in as needed.
    Return value has to be a valid python dictionary with two customary keys:
        - loss: Specify a numeric evaluation metric to be minimized
        - status: Just use STATUS_OK and see hyperopt documentation if not feasible
    The last one is optional, though recommended, namely:
        - model: specify the model just created so that we can later use it again.
    """
    model = Sequential()
    model.add(Dense(512, input_shape=(784,)))
    model.add(BatchNormalization())
    model.add(Activation(space['Activation']))
    model.add(Dropout(space['Dropout']))

    model.add(Dense(space['Dense']))
    model.add(BatchNormalization())
    model.add(Activation(space['Activation_1']))
    model.add(Dropout(space['Dropout_1']))

    for _ in range(1, conditional(space['conditional'])):
        model.add(Dense(space['Dense_1']))
        model.add(BatchNormalization())
        model.add(space['add'])
        model.add(Activation('relu'))

    model.add(Dense(10))
    model.add(BatchNormalization())
    model.add(Activation('softmax'))

    model.compile(loss='categorical_crossentropy', metrics=['accuracy'],
                  optimizer=space['optimizer'])

    model.fit(X_train, Y_train,
              batch_size=space['batch_size'],
              nb_epoch=1,
              verbose=2,
              validation_data=(X_test, Y_test))
    score, acc = model.evaluate(X_test, Y_test, verbose=0)
    print('Test accuracy:', acc)
    return {'loss': -acc, 'status': STATUS_OK, 'model': model}

def get_space():
    return {
        'Activation': hp.choice('Activation', ['relu', 'softplus', 'softsign']),
        'Dropout': hp.uniform('Dropout', 0, 0.5),
        'Dense': hp.choice('Dense', [32, 64, 128, 256, 512, 768, 1024]),
        'Activation_1': hp.choice('Activation_1', ['relu', 'sigmoid', 'hard_sigmoid', 'softmax', 'tanh', 'softplus', 'softsign']),
        'Dropout_1': hp.uniform('Dropout_1', 0, 0.5),
        'conditional': hp.choice('conditional', [1, 4, 8, 16]),
        'Dense_1': hp.choice('Dense_1', [32, 64, 128, 256, 512, 768, 1024]),
        'add': hp.choice('add', [Dropout(0.5), Dropout(0.25),
                            Activation('linear'), Activation('relu'), Activation('hard_sigmoid'), Activation('softmax')]),
        'optimizer': hp.choice('optimizer', ['rmsprop', 'adam', 'sgd', 'nadam', 'adadelta', 'adamax', 'adagrad']),
        'batch_size': hp.choice('batch_size', [64, 128, 256, 512, 768, 1024]),
    }

`

As you see, there is no imports from keras at all :(

**Comment by maxpumperla** [comment] 2016-12-05 14:59
huh, strange... and what's the stack trace?

**Comment by ErmiaAzarkhalili** [comment] 2016-12-05 15:06
Unexpected error: <class 'NameError'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-51179d7d914a>", line 86, in <module>
    trials=Trials(), notebook_name="simple_notebook")
  File "/usr/local/lib/python3.4/dist-packages/hyperas/optim.py", line 42, in minimize
    notebook_name=notebook_name, verbose=verbose)
  File "/usr/local/lib/python3.4/dist-packages/hyperas/optim.py", line 67, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space
  File "/home/user/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/163.8233.8/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/user/Desktop/PycharmProjects/DeepLearning/temp_model.py", line 10, in <module>
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
NameError: name 'mnist' is not defined

**Comment by ErmiaAzarkhalili** [comment] 2016-12-05 15:59
get the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-482b4a12f9e5>", line 86, in <module>
    trials=Trials())
  File "/usr/local/lib/python3.4/dist-packages/hyperas/optim.py", line 42, in minimize
    notebook_name=notebook_name, verbose=verbose)
  File "/usr/local/lib/python3.4/dist-packages/hyperas/optim.py", line 62, in base_minimizer
    model_str = get_hyperopt_model_string(model, data, notebook_name, verbose, stack)
  File "/usr/local/lib/python3.4/dist-packages/hyperas/optim.py", line 125, in get_hyperopt_model_string
    with open(calling_script_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Desktop/PycharmProjects/DeepLearning/<ipython-input-2-482b4a12f9e5>'

**Comment by maxpumperla** [comment] 2016-12-06 06:18
I can't reproduce the error, works fine for me. However, I think the problem has to do with how you run this on your side and the call stack this produces. It seems hyperas doesn't pick up the correct file to read imports from. In terms of code it means that in this line:

https://github.com/maxpumperla/hyperas/blob/master/hyperas/optim.py#L124

the variable `stack` seems wrong. When you add

```{python}
for item in inspect.stack():
    print(item[1])
```
into the code just before that line, at which position does the script you want to run (i.e. the file where hyperas code resides) pop up?

**Comment by ErmiaAzarkhalili** [comment] 2016-12-06 06:45
could you please provide me with the exact code here and the name of all files you have into your pycharm running folder?

**Comment by ErmiaAzarkhalili** [comment] 2016-12-06 14:01
Hi when I run the file from tab "Run" in the menu (shift+F10), everything looks great and is working fine.
but, when I select the whole code in the script and aim to run it via Alt+Shift+E (the shortcut key of execution selection in console), it raise an error as before...

Reason: in the first case, it is exactly run 
/usr/bin/python3.4 /home/user/PycharmProjects/DeepLearning/hyperas-test.py
which have to properly work...

but, what is happening when I utilize python console in pycharm? I checked and am sure that it utilized the same python version...

Completely confused... is it really hyperas problem? am not sure at all...pycharm problem? may be! will investigate more...

**Comment by maxpumperla** [comment] 2016-12-10 17:21
Hmm, that's exactly why I wanted to know how exactly you were using your IDE. So, essentially your command above takes all code and pastes it in an active ipython session. For sure that will not work. Why? Hyperas needs to inspect the code of the python file you're executing. An ipython session is only temporarily persisted. You can access what you pasted in by using the magic function `% history`, but that's not helping much here.

Why don't you just run the shortcut that works? It's the more reliable way in any case.

**Comment by ErmiaAzarkhalili** [comment] 2016-12-10 17:29
You're right Max.
Your explanation is fully understandable, but please kindly add this note to your guide and documentation.

I will also provide more examples to hyperas very soon.

PS: May I open a new issue for advanced layers or reopen the existed one?

⁣Best Regard,
Behrooz​

**Comment by maxpumperla** [comment] 2017-06-11 13:49
will close this in favour of #101, we don't support pycharm right now, I'm afraid.

**Closed by maxpumperla** 2017-06-11 13:49 UTC
